# Prime's config

# Base theme (fallback)
# include ./kitty-themes/00-Default.conf

font_family "FantasqueSansM Nerd Font Mono Bold", "Font Awesome 6 Free"
font_size 14.0
bold_font auto
italic_font auto
bold_italic_font auto

background_opacity 0.9
dynamic_background_opacity yes
confirm_os_window_close 0

# Animated cursor
cursor_trail 1

# Display server
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no
window_padding_width 4

# Kitty remote control for pywal
listen_on unix:/tmp/kitty_pywal
allow_remote_control yes

# BEGIN_KITTY_THEME
# Modus Vivendi (kitty theme switcher)
# include current-theme.conf
# END_KITTY_THEME

# === PYWAL COLORS (MUST BE LAST) ===
include ~/.cache/wal/colors-kitty.conf

